INSERT INTO users (name, age) VALUES ("Naruto Uzumaki", 15);
INSERT INTO users (name, age) VALUES ("Hinata Hyuga", 15);
INSERT INTO users (name, age) VALUES ("Shikamaru Nara", 15);
INSERT INTO users (name, age) VALUES ("Sasuke Uchiha", 15);
INSERT INTO users (name, age) VALUES ("Sakura Haruno", 15);
INSERT INTO users (name, age) VALUES ("Rock Lee", 16);
INSERT INTO users (name, age) VALUES ("Neji Hyuga", 16);
INSERT INTO users (name, age) VALUES ("Kakashi Hatake", 25);
INSERT INTO users (name, age) VALUES ("Minato Namikaze", 30);
INSERT INTO users (name, age) VALUES ("Shino Aburame", 15);
INSERT INTO users (name, age) VALUES ("Ino Yamanaka", 15);
INSERT INTO users (name, age) VALUES ("Kiba Inuzuka", 15);
INSERT INTO users (name, age) VALUES ("Itachi Uchiha", 20);
INSERT INTO users (name, age) VALUES ("Hashirama Senju", 50);
INSERT INTO users (name, age) VALUES ("Madara Uchiha", 50);
INSERT INTO users (name, age) VALUES ("Kushina Uzumaki", 30);
INSERT INTO users (name, age) VALUES ("Choji Akimichi",  15);
INSERT INTO users (name, age) VALUES ("Tenten", 15);
INSERT INTO users (name, age) VALUES ("Gaara", 15);
INSERT INTO users (name, age) VALUES ("Might Guy", 25);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save Sasuke", "Rescue", 5000, "May 2016", "January 2018" );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Protect Naruto", "Protectiton", 5000, "March 2010", "January 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Protect the Leaf Village", "Protectiton", 10000, "July 2017", "January 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rebuild the Leaf Village", "Repair", 20000, "May 2016", "January 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save Gaara", "Rescue", 7500,"August 2016", "January 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Recruit Tsunade", "Recruitment", 8000, "May 2016", "January 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Team 7 Training", "Training", 2000, "May 2016", "January 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Chunin Exam", "Promotion", 50000, "May 2016", "January 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("First Mission", "Protection", 4000,"June 2014", "January 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Ninja World", "Protection", 1000000, "Febuary 2018", "December 2018");

INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30000, 4, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2500, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
-- INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 10);
;
